### ISSUE TITLE
ValueError: DEP_TIME

### ISSUE THREAD

**Issue by mshearer0** [GoogleCloudPlatform/data-science-on-gcp#10]
Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/rdd.py", line 1339, in takeUpToNumLeft
  File "/tmp/7fa836049f5f469b85f5eb082a72c77c/logistic.py", line 92, in to_example
    features.extend(get_local_hour(fields['DEP_TIME'],
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/sql/types.py", line 1491, in __getitem__
    raise ValueError(item)
ValueError: DEP_TIME

**Comment by lakshmanok** [comment]
It works for me.  

The error message seems to indicate the input path was wrong in some way.

**Comment by mshearer0** [comment]
Just checked and still get same error running ./submit_spark.sh cloud-training-demos-ms experiment.py from 07_sparkml

[DEP_TIME.txt](https://github.com/GoogleCloudPlatform/data-science-on-gcp/files/1958583/DEP_TIME.txt)
