### ISSUE TITLE
chapter 04 - python3 ./simulate.py is not working

### ISSUE THREAD

**Issue by aatsoares** [GoogleCloudPlatform/data-science-on-gcp#103]
I am trying run the simulate.py in command line:

python3 ./simulate.py --startTime '2015-05-01 00:00:00 UTC' --endTime '2015-05-04 00:00:00 UTC' --speedFactor=30 --pro
ject $DEVSHELL_PROJECT_ID

However, the output is a error list as following (google cloud shell): 

Traceback (most recent call last):
  File "./simulate.py", line 118, in <module>
    publisher.get_topic(topics[event_type])
  File "/home/andre_t_soares/.local/lib/python3.7/site-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/home/andre_t_soares/.local/lib/python3.7/site-packages/google/pubsub_v1/services/publisher/client.py", line 537, in get_topic
    request = pubsub.GetTopicRequest(request)
  File "/usr/local/lib/python3.7/dist-packages/proto/message.py", line 412, in __init__
    % (self.__class__.__name__, mapping,)
TypeError: Invalid constructor input for GetTopicRequest: 'projects/lab-data-science/topics/wheelsoff'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./simulate.py", line 120, in <module>
    publisher.create_topic(topics[event_type])
  File "/home/andre_t_soares/.local/lib/python3.7/site-packages/google/cloud/pubsub_v1/_gapic.py", line 40, in <lambda>
    fx = lambda self, *a, **kw: wrapped_fx(self.api, *a, **kw)  # noqa
  File "/home/andre_t_soares/.local/lib/python3.7/site-packages/google/pubsub_v1/services/publisher/client.py", line 332, in create_topic
    request = pubsub.Topic(request)
  File "/usr/local/lib/python3.7/dist-packages/proto/message.py", line 412, in __init__
    % (self.__class__.__name__, mapping,)
TypeError: Invalid constructor input for Topic: 'projects/lab-data-science/topics/wheelsoff'

Please, can anyone give an advice about how to fix it?

**Comment by lakshmanok** [comment]
PR #102 should fix this.
