### ISSUE TITLE
error with 04_streaming/simulate/df06.py (similar to #56)

### ISSUE THREAD

**Issue by pagestarr66** [GoogleCloudPlatform/data-science-on-gcp#58]
Hi I am getting the same error as reported in #56 for df05.py, but am running on my own GCP platform account for df06.py.  Error snippet is below.

File "/usr/local/lib/python2.7/dist-packages/apache_beam/transforms/core.py", line 1161, in <lambda> wrapper = lambda x: [fn(x)] File "df06.py", line 134, in <lambda> | 'airports:tz' >> beam.Map(lambda fields: (fields[0], addtimezone(fields[21], fields[26]))) File "df06.py", line 24, in addtimezone import timezonefinder File "/usr/local/lib/python2.7/dist-packages/timezonefinder/__init__.py", line 2, in <module> from .timezonefinder import TimezoneFinder File "/usr/local/lib/python2.7/dist-packages/timezonefinder/timezonefinder.py", line 300 def closest_timezone_at(self, *, lat, lng, delta_degree=1, exact_computation=False, return_distances=False, ^ SyntaxError: invalid syntax [while running 'airports:tz']

**Comment by pagestarr66** [comment]
I tried applying the df05.py change to df06.py but now have a different error on the Cloud Shell (it doesn't run on dataflow):

Correcting timestamps and writing to BigQuery dataset flights
WARNING:root:The DirectPipelineResult is being garbage-collected while the DirectRunner is still running the corresponding pipeline. This may lead to incomplete execution of the pipeline if the main thread exits before pipeline completion
. Consider using result.wait_until_finish() to wait for completion of pipeline execution.
Exception in thread Thread: 0, ExecutorServiceWorker-0 (executing) (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/direct/executor.py", line 97, in run
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/runners/direct/executor.py", line 347, in call
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'error'

**Comment by silverlightweb** [comment]
Hi @pagestarr66 . I have the same problem with you. I solved that problem by the way change 'timezonefinder' in the "setup.py" to "timezonefinder <= 3.0.0".
