### ISSUE TITLE
Need to specify project id in bq.Client()

### ISSUE THREAD

**Issue by anagrawa** [GoogleCloudPlatform/data-science-on-gcp#7]
This is the error seen:
agrawalankit@test-aagrawal:~/data-science-on-gcp/04_streaming/simulate$ python ./simulate.py --startTime '2015-05-01 00:00:00 UTC' --endTime '2015-05-04 00:00:00 UTC' --speedFactor=60 --project test-aagrawal
Traceback (most recent call last):
  File "./simulate.py", line 83, in <module>
    dataset =  bqclient.get_dataset( bqclient.dataset('flights') )  # throws exception on failure
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/bigquery/client.py", line 288, in get_dataset
    path=dataset_ref.path)
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/bigquery/client.py", line 271, in _call_api
    return call()
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/retry.py", line 260, in retry_wrapped_func
    on_error=on_error,
  File "/usr/local/lib/python2.7/dist-packages/google/api_core/retry.py", line 177, in retry_target
    return target()
  File "/usr/local/lib/python2.7/dist-packages/google/cloud/_http.py", line 293, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.NotFound: 404 GET https://www.googleapis.com/bigquery/v2/projects/no-project-id/datasets/flights: Not found: Project no-project-id

The fix should be update line 83 of simulate.py as:

bqclient = bq.Client(project=args.project)

**Comment by lakshmanok** [comment]
thanks, fixed.
